### ISSUE TITLE
Bug with unmatched chunks

### ISSUE THREAD

**Issue by lionel-** [phillord/lentic#40] opened 2015-09-07 10:57 UTC
It happens when two different types of blocks are used.

To reproduce, copy the following in a new `.org` file:
```org
#+BEGIN_SRC clojure
(some-code)
#+END_SRC

#+BEGIN_SRC other-lang
example
#+END_SRC

# Local Variables:
# lentic-init: lentic-org-clojure-init
# End:
```
Then:

* create a lentic buffer and switch to it
* make a change in the buffer.

This results in the original creator buffer getting commented everywhere. It also does weird things to the undo history and it's not possible to get back to the original text.

**Comment by phillord** [comment] 2015-09-07 15:27
Thanks for the report, I've reproduced the behaviour now. Not sure of the cause yet, but will investigate when I can.

**Comment by phillord** [comment] 2015-09-09 10:27
Found the cause -- the "invert" function is wrong, so it's running an
unmatched transform in one direction and matched in the other.

Thinking about a solution, but it's not going to be immediate, I am
afraid.

Phil

**Comment by phillord** [comment] 2015-12-23 09:13
This should be fixed now, I believe. The "weird things with the undo" should also be fixed also, but am afraid this required core emacs updates -- so it will only be on Emacs-25.

**Comment by lionel-** [comment] 2015-12-23 12:16
Thanks a lot Phil! I saw you struggle on emacs-devel with that undo thing ;) Glad it's worked out.

**Comment by phillord** [comment] 2015-12-23 14:20
Took a bit longer than I expected, I have to admit, but I learned a lot and Stefan was tremendously helpful. Looks like master is still broken as a result, though! Oh dear.

**Closed by phillord** 2015-12-23 14:20 UTC
