### ISSUE TITLE
The problem of Head1 with tags

### ISSUE THREAD

**Issue by tumashu** [phillord/lentic#33] opened 2015-05-12 23:56 UTC
```
* fff-fff                                                              :test:
```
This get the unexpected results: 
```
;;; fff:-fff                                                              :test:
```

**Comment by phillord** [comment] 2015-05-13 08:05
Hmm, tricky. The problem is that "-" is not word syntax in org-mode, although the reverse transformation works because it is word syntax in emacs-lisp mode.

Of course, I can just add "-" to the match, but that will only work for "-". Do you have any other characters you want?

Or alternatively, I could try and change the regexp to match anything except for ";" , ":" or space.

Or, I could match spaces also. This would also allow me to match 

    * Multi Word Lines                         :with-tags:

Although, I can't think how I can identify the end of the last word here, at least not with a regexp.

**Comment by tumashu** [comment] 2015-05-14 00:49
```
Or alternatively, I could try and change the regexp to match anything except for ";" , ":" or space.
```
I think this is a good idea, but stable and consistent is more important.

**Comment by phillord** [comment] 2015-05-14 08:04
Yes, I agree -- and  it turns out that multi-word lines is a bit of a pain. I'm am more inclined to just support "-", although for my use of the org -> transformation I just use the "standard" headers "Commentary, Code" and so on.

Shall we leave things as they are for now, till there is a more compelling use case?

**Comment by tumashu** [comment] 2015-05-14 23:17
if head1 has tags, don't convert its * to   ";;;", just add "#".  can this approach solve the issue

**Comment by tumashu** [comment] 2015-05-14 23:29
another approach is: add a custom list, convert its element to head1, then we can add ";;;head;" ";;;commentary;" to this list, this may be a simper way

**Comment by phillord** [comment] 2015-05-15 11:22
This would mean that you couldn't call but tags on Code::: headers.

The easiest way to achieve this is to just not use Head 2 which uses
this transformation. Or just use the org->el transformation which does
not special head 1 transform.

tumashu <notifications@github.com> writes:

> if head1 has tags, don't convert its * to   ";;;", just add "#".  can this approach solve the issue
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/phillord/lentic/issues/33#issuecomment-102197096

-- 
Phillip Lord,                           Phone: +44 (0) 191 208 7827
Lecturer in Bioinformatics,             Email: phillip.lord@newcastle.ac.uk
School of Computing Science,            http://homepages.cs.ncl.ac.uk/phillip.lord
Room 914 Claremont Tower,               skype: russet_apples
Newcastle University,                   twitter: phillord
NE1 7RU

**Comment by phillord** [comment] 2015-05-15 11:22
I'm wary of that one because its even more restrictive than the current
"single word header 1" rule.

**Comment by tumashu** [comment] 2015-05-15 12:05
```
I'm wary of that one because its even more restrictive than the current "single word header 1" rule. 
```

Yes， but i think it can be regard as "org->el" enhance, but more comfortable, the reason is that:

1.  I think "org -> el" is more stable and consistent than "orgel -> el".
2.  head1 is often ";;;head:" ";;;commary;" ";;;Codes:"  and ":;;Footer:",  custom head1 is seldom used in elisp file.
3.  If I want to custom head1, I can use this style, which very very easy to deal with by org-mode
```
;;; Codes:
;;* This is codes head1 :export
;;   xxxxxx
```
output:
```
* Code:
* This is codes head1 :export
xxxxxx
```

**Comment by tumashu** [comment] 2015-05-15 12:07
If i want to a clean org file, i just export to org file....

**Comment by tumashu** [comment] 2015-05-15 12:14
```
This would mean that you couldn't call but tags on Code::: headers. 
```
I don't need to add tags to "Codes:", i just use follow tips and can use a beautiful head1.
```
;;; Codes:
;; * This is my Codes head  :export:

```

```
 Or just use the org->el transformation which does not special head 1 transform. 
```

org->el has follow issue:

1.  can't deal with  first line.
2.  "Header" ""Codes" "Commentary" and "Footer"  convert as paragraphy, need use regexp-replace
     to deal with.

**Comment by tumashu** [comment] 2015-05-15 12:23
Maybe we can add another transformation method, for example: "org->el++"

**Comment by phillord** [comment] 2015-05-15 13:10
Yes, I agree, that "Code:", "Commentary:" and my own "Header" and "Footer" are perhaps the only ones we need. And, as you say, we can add "normal" header one in other ways. I will think on this, but it does seem to be a reasonable solution to the problem. It would probably simplify the code also.

On the first line issue for org->el I am not hugely keen on fixing this. It adds complexity and sort of defeats the point of having the orgel transformation.

**Comment by tumashu** [comment] 2015-09-10 02:38
Is the status of this ？

**Comment by phillord** [comment] 2015-09-10 07:21
Well, we have tags on H1, but only single word H1. You can't put dashes in words.

To be honest, at the moment, I think that this is the best compromise, and I am not planning to restrict H1 to specified words. I'd be willing to take a patch which supports "-".

**Comment by tumashu** [comment] 2015-10-10 12:08
i want to code and maintain my own version:

1.  base on org-el
2.  deal with header, Codes, Commentary, and Footer

but have failed, could you help me?

**Comment by phillord** [comment] 2015-10-12 12:29
I am happy to help with any problems that you have, within reason.

Phil

tumashu <notifications@github.com> writes:

> i want to code and maintain my own version:
>
> 1.  base on org-el
> 2.  deal with header, Codes, Commentary, and Footer
>
> but have failed, could you help me?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/phillord/lentic/issues/33#issuecomment-147082298

-- 
Phillip Lord,                           Phone: +44 (0) 191 208 7827
Lecturer in Bioinformatics,             Email: phillip.lord@newcastle.ac.uk
School of Computing Science,            http://homepages.cs.ncl.ac.uk/phillip.lord
Room 914 Claremont Tower,               skype: russet_apples
Newcastle University,                   twitter: phillord
NE1 7RU

**Comment by tumashu** [comment] 2015-10-14 12:35
Finally, I realized that "el-org" is more convenient than ‘’orgel-org“ with the help of tip,

```
;;; Codes:
;; * This is my code     :code:
```

I will use "el-org" and hack org-exporter, this seem more easy and stable

**Comment by tumashu** [comment] 2015-10-14 13:04
```
;;; chinese-pyim-core.el --- The core of Chinese pinyin input method

```
As for the above problem, may be i can use "before-save-hook"..

**Comment by phillord** [comment] 2015-10-15 10:57
tumashu <notifications@github.com> writes:

> ```
> ;;; chinese-pyim-core.el --- The core of Chinese pinyin input method
>
> ```
> As for the above problem, may be i can use "before-save-hook"..


I've rather lost context here. Is this a question?

**Comment by tumashu** [comment] 2015-10-15 13:24
now i think el-org  is more stable than orgel-org,  one problem is  that ";;;" will be translate to ";; ;;;",  i want to deal with it  by  before-save-hook ,but fail

**Comment by tumashu** [comment] 2015-10-15 13:30
i just want  "el-org" + ";;, ;;; fix",

**Comment by phillord** [comment] 2015-10-15 14:01
tumashu <notifications@github.com> writes:

> now i think el-org is more stable than orgel-org,

Yes, that's undoubtedly true. It's simpler, which makes stability more
straight-forward.

> one problem is that ";;;" will be translate to ";; ;;;", i want to
> deal with it by before-save-hook ,but fail


Well, the code to detal with that is in orgel-org. Not sure using
before-save-hook will help -- any changes you make there will be
percolated by lentic.

Phil

**Comment by tumashu** [comment] 2015-10-19 01:20
Thanks for help, the below is the code i current use.
```
(use-package lentic
  :ensure nil
  :config

  (defclass lentic-org2el-configuration
    (lentic-unmatched-chunk-configuration
     lentic-uncommented-chunk-configuration)
    ())

  (defun lentic-org2el--fixup-extra-semicolon (conf)
    "Fixup ';; ;;;'."
    (m-buffer-replace-match
     (m-buffer-match
      (lentic-that conf)
      "^;; ;;; ")
     ";;; "))

  (defmethod lentic-clone
    ((conf lentic-org2el-configuration)
     &optional start stop length-before
     start-converted stop-converted)
    ;; do everything else to the buffer
    (m-buffer-with-markers
        ((first-line
          (m-buffer-match-first-line
           (lentic-this conf)))
         (header-one-line
          (m-buffer-match
           (lentic-this conf)
           (rx line-start
               "* " (0+ word)
               (optional (1+ " ")
                         ":" (1+ word) ":")
               line-end)
           :begin (cl-cadar first-line)))
         (special-lines
          (-concat first-line header-one-line)))
      ;; check whether we are in a special line -- if so widen the change extent
      (let* ((start-in-special
              (when (and start
                         (m-buffer-in-match-p
                          special-lines start))
                (m-buffer-at-line-beginning-position
                 (lentic-this conf)
                 start)))
             (start (or start-in-special start))
             (start-converted
              (if start-in-special
                  (m-buffer-at-line-beginning-position
                   (lentic-that conf)
                   start-converted)
                start-converted))
             (stop-in-special
              (when (and stop
                         (m-buffer-in-match-p
                          special-lines stop))
                (m-buffer-at-line-end-position
                 (lentic-this conf)
                 stop)))
             (stop (or stop-in-special stop))
             (stop-converted
              (if stop-in-special
                  (m-buffer-at-line-end-position
                   (lentic-that conf)
                   stop-converted)
                stop-converted))
             (clone-return
              (call-next-method conf start stop length-before
                                start-converted stop-converted))
             (c1 (lentic-org2el--fixup-extra-semicolon conf)))
        (if (or start-in-special stop-in-special c1)
            nil
          clone-return))))

  (defmethod lentic-convert
    ((conf lentic-org2el-configuration)
     location)
    (let ((converted (call-next-method conf location)))
      (m-buffer-with-current-position
          (oref conf :this-buffer)
          location
        (beginning-of-line)
        (if (looking-at
             (rx (submatch "* ")
                 (submatch (1+ word))
                 (optional (1+ " ")
                           ":" (1+ word) ":")
                 line-end))
            (cond ((= location (nth 2 (match-data)))
                   (m-buffer-at-line-beginning-position
                    (oref conf :that-buffer)
                    converted))
                  ((< location (nth 5 (match-data)))
                   (- converted 1))
                  (t converted))
          converted))))

  (defmethod lentic-invert
    ((conf lentic-org2el-configuration))
    (lentic-m-oset
     (lentic-el2org-init)
     :that-buffer
     (lentic-this conf)))

  (defun lentic-org2el-and-el2org-oset (conf)
    (lentic-m-oset
     conf
     :this-buffer (current-buffer)
     :comment ";; "
     :comment-stop "#\\\+BEGIN_SRC emacs-lisp.*"
     :comment-start "#\\\+END_SRC"))

;;;###autoload
  (defun lentic-org2el-init ()
    (lentic-org2el-and-el2org-oset
     (lentic-org2el-configuration
      "lb-org2el"
      :lentic-file
      (concat
       (file-name-sans-extension
        (buffer-file-name))
       ".el"))))

  (add-to-list 'lentic-init-functions
               'lentic-org2el-init)

  (defclass lentic-el2org-configuration
    (lentic-unmatched-chunk-configuration
     lentic-commented-chunk-configuration)
    ())

  (defmethod lentic-invert
    ((conf lentic-el2org-configuration))
    (lentic-m-oset
     (lentic-org2el-init)
     :delete-on-exit t
     :that-buffer (lentic-this conf)))

;;;###autoload
  (defun lentic-el2org-init ()
    (lentic-org2el-and-el2org-oset
     (lentic-el2org-configuration
      "lb-el2org"
      ;; we don't really need a file and could cope without, but org mode assumes
      ;; that the buffer is file name bound when it exports. As it happens, this
      ;; also means that file saving is possible which in turn saves the el file
      :lentic-file
      (concat
       (file-name-sans-extension
        (buffer-file-name))
       ".org"))))

  (add-to-list 'lentic-init-functions
               'lentic-el2org-init)
  )

```

**Comment by tumashu** [comment] 2015-10-19 01:22
```
(defun my-org-preprocess (backend)
  "This function delete useless string."
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "^;;; +Commentary:.*" nil t)
      (replace-match "" nil t))
    (goto-char (point-min))
    (while (re-search-forward "^;;; +Code:.*" nil t)
      (replace-match "" nil t))))

(add-hook org-export-before-processing-hook 'my-org-preprocess)
```

**Comment by tumashu** [comment] 2015-10-19 08:41
The below is the code current used， any suggestion？ thanks！

https://github.com/tumashu/emacs-helper/blob/master/eh-lentic.el

**Comment by phillord** [comment] 2015-10-20 09:28
If you are after general suggestions, then I wouldn't nest all of this
in a use-package macro. I am not sure what the eh-lentic function is
doing -- if there is something about the UI that you don't like, then
let me know and I will incorporate. The rest seems okay.

Or is it broken?

**Comment by tumashu** [comment] 2015-10-20 12:16
"eh-lentic" is my own quick lentic command, which just "split-below" and "active the below window"
maybe  "eh-lentic-switch-window" is a good name.

**Comment by tumashu** [comment] 2015-10-20 12:26
At the moment, my project "Chinese-pyim" is using "lentic-el2org-init", and works well:
https://github.com/tumashu/chinese-pyim

This is my custom lentic-doc :-)
https://github.com/tumashu/chinese-pyim/blob/master/chinese-pyim-devtools.el

This is the website generated from elisp with the help of lentic and org-webpage
http://tumashu.github.io/chinese-pyim/

**Comment by tumashu** [comment] 2015-10-20 12:32
![test7](https://cloud.githubusercontent.com/assets/67725/10606993/16504f82-7769-11e5-8431-90de09232239.gif)

**Comment by phillord** [comment] 2015-10-20 19:19
Thanks for uploading the git, it's really nice to see lentic in action for someone else. If you have the time, you couldn't do a brief gif using chinese-pyim? I'd love to see lentic working with a non-latin character set.

**Comment by tumashu** [comment] 2015-10-21 06:37
![test11](https://cloud.githubusercontent.com/assets/67725/10629326/6a66f84a-7800-11e5-9e8e-93a5bb3a6bee.GIF)

OK!

**Comment by tumashu** [comment] 2015-10-21 06:41
![test11](https://cloud.githubusercontent.com/assets/67725/10629460/a08d0cc4-7801-11e5-8ce1-9eab0408bc03.gif)

OK!

**Comment by tumashu** [comment] 2015-10-21 06:46
gif is too big, suggest download and view.

**Comment by tumashu** [comment] 2015-10-23 08:57
I have changed my lentic config a little,  now i only use a command `eh-lenitc-switch-window' to do all my lentic switch work, very easy use, this command is bound to 'C-c j',  This behavier is more like `org-edit-special' 

![2](https://cloud.githubusercontent.com/assets/67725/10688400/ace40c06-79a6-11e5-95f4-00c662c5dbc4.gif)

**Comment by phillord** [comment] 2015-10-23 09:25
I switch views on F1 - although I normally look at one view at a time.

These gifs are really, really nice. Do you mind if I use them from my lentic front page?

**Comment by tumashu** [comment] 2015-10-23 12:37
Feel free to use these gifs

**Comment by tumashu** [comment] 2015-10-24 00:38
by the way， my own `lentic-el2org-init‘ is very similar `lentic-el-org-init’， is it possible to merge it to
·lentic-el-org-init‘？  if not， I will build a new melpa package to hold `lentic-el2org-init',  this package's feature will be like el2markdown.

**Comment by phillord** [comment] 2015-10-26 11:49
Not sure how I could merge these to be honest. I could do this...

    (defun lentic-org-oset (conf)
      (lentic-m-oset
       conf
       :this-buffer (current-buffer)
       :comment ";; "
       :comment-stop "#\\\+BEGIN_SRC emacs-lisp.*"
       :comment-start "#\\\+END_SRC"
       :lentic-file (concat
         (file-name-sans-extension
          (buffer-file-name))
         ".el")))
    
Which would make org-el-init this.

    (defun lentic-org-el-init ()
      (lentic-org-oset
       (lentic-unmatched-uncommented-chunk-configuration
        "lb-org-to-el")))

and likewise for el-org-init. This would reduce your own
lentic-el2org-init as well.

Phil

**Comment by tumashu** [comment] 2015-11-22 12:44
now, i refactor my lentic config， as a module of org-webpage,  which only focus write org format comment , simple and useful...

**Comment by tumashu** [comment] 2015-11-22 12:45
https://github.com/tumashu/org-webpage/blob/master/owp-lentic.el

**Comment by phillord** [comment] 2015-11-25 13:39
It's nice to see that it is working well for you!

**Comment by tumashu** [comment] 2016-01-03 02:07
i have refacted my owp-lentic.el file to a new package: easy-lentic. may be you are interesting it too...
https://github.com/tumashu/easy-lentic

**Comment by phillord** [comment] 2016-01-20 20:40
It's good that this is all working for you. I've been debating adding tools for adding markers, but haven't as I just use yasnippet, or org-mode tools but see you have done this already.

Will close this now, as I don't think it's outstanding, but feel free to re-open.

**Closed by phillord** 2016-01-20 20:40 UTC

**Comment by tumashu** [comment] 2016-01-20 23:49
Ok, thanks for your help!
